services:
  app:
    build:
      context: ./app
    environment:
      DATA_DIR: /home/data
    restart: always
    volumes:
      - ./data:/home/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data:/home/data