services:
  app:
    build: ./app
    environment:
      DATA_DIR: /home/data
    restart: always
    volumes:
      - ./data:/home/data

  nginx:
    build: ./nginx
    environment:
      DATA_DIR: /home/data
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./data:/home/data